version: "3.8"

services:
  nginx:
    image: ichi-flask-challenge:nginx
    # command: 
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./web/env/nginx:/etc/nginx/conf.d
    depends_on:
      - api
    logging:
      driver: "none"
    restart: always
    networks:
      - services

  api:
    image: ichi-flask-challenge:python-3.7.10-slim-buster
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    command: >
      python main.py
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    working_dir: /api/src
    logging:
      driver: json-file
    environment:
      - APP_STAGE=local
      - LOG_LEVEL=debug
      - MYSQL_CONNECTION
    depends_on:
      - db
    # restart: always
    networks:
      - services

  db:
    image: mysql:5.7
    # build: ./docker/mysql
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqlshow -u ${MYSQL_USER} -p${MYSQL_PASSWORD}"]
    #   interval: "5s"
    #   retries: 10
    logging:
      driver: "none"
    restart: always
    networks:
      - services
    
networks:
  services:
    external:
      name: flask_challenge_networks
